### ISSUE TITLE
docs: ledger-mode comparison

### ISSUE THREAD

**Issue by simonmichael** [narendraj9/hledger-mode#1]
Thanks for maintaining this!

As a user of ledger-mode, I'm curious how they compare. What's the same, what can I do in one but not the other, why did you start this one etc. Could you add this to the docs ?

**Comment by narendraj9** [comment]
Sure will do. 

To be brief, I didn't know about ledger-mode when I starting writing hledger-mode. 
Things that hledger-mode does

1. In some reports, it sorts the amounts inside emacs because hledger doesn't have support for sorting.
2. It is designed to make it easier for me to do this. So, to keep things simple one should start with calling the command `hledger-jentry` and hitting [Tab] should do what is expected, e.g. insert date. I don't think this is where it differs from ledger-mode.
3. It has functions for emailing you the reports [An overall report I like to call] to yourself every month. You will need to setup email api credentials. I use the mailgun api. It's free and easy to configure. 
4. I have added a few financial ratios that help we keep track of my financial help, e.g. Liquidity ratio aka  Emergency fund ratio. Savings ratio. Current ratio. They are in the overall report. 
5. It will grow with me as I become more mature because I understand everything about how it is written.

**Comment by narendraj9** [comment]
Disclaimer: I have never used ledger-mode myself.

**Comment by narendraj9** [comment]
I think I should study ledger-mode and incorporate things I find good there. It looks very featureful.

**Comment by cmal** [comment]
I've been using `ledger` and `ledger-mode` for years. `ledger` has so many features but I only know and use a few of them. The `ledger-mode` is easy to use and very good. But I find `ledger` and `ledger-mode` lacks something that I can use it as my wish. For example, I cannot transpose transactions, I can only kill and yank to change the positions of them in `ledger-mode`. And I cannot generate a income sheet between some period. (Maybe because I do not know much of the ledger-cli).  I find `hledger` uses similar format of text to record journal. So I wonder whether `hledger` gives the compatibility to use `ledger` files and so I can use my old ledger files for `hledger` without convert and I hope `hledger` give me a nice user experience. And It seems it is very likely.

**Comment by narendraj9** [comment]
@cmal I think you should be able to use your ledger files with hledger without any modification.

**Comment by cmal** [comment]
@narendraj9 Oh, that is great. I'll try to use `hledger`. I've found it has amazing interactive commands and beautiful UIs and hope I no longer need to write `ledger-cli` command anymore.
